# Generated by Django 4.2.16 on 2024-11-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactmodel_creation_date_alter_contactmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
